// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCXm4MHsJt-PctoV03qIxaybMpLB-6vZ_A',
    appId: '1:716879445462:web:a8c07945afddf239307877',
    messagingSenderId: '716879445462',
    projectId: 'infinityfeedflutterapp',
    authDomain: 'infinityfeedflutterapp.firebaseapp.com',
    storageBucket: 'infinityfeedflutterapp.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAw-cnzCrXyLaWaazBL34Q2qbopukXIBRA',
    appId: '1:716879445462:android:31979e4ba3020ed4307877',
    messagingSenderId: '716879445462',
    projectId: 'infinityfeedflutterapp',
    storageBucket: 'infinityfeedflutterapp.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCkTnT9Vv5ouNTSMqgKGA2dO78lbljvPwQ',
    appId: '1:716879445462:ios:6e290561645247d6307877',
    messagingSenderId: '716879445462',
    projectId: 'infinityfeedflutterapp',
    storageBucket: 'infinityfeedflutterapp.appspot.com',
    iosClientId: '716879445462-7dnq6j32eqm8i73rkijbqcm6k43nafh6.apps.googleusercontent.com',
    iosBundleId: 'com.example.instagram',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCkTnT9Vv5ouNTSMqgKGA2dO78lbljvPwQ',
    appId: '1:716879445462:ios:92caca42a4878f04307877',
    messagingSenderId: '716879445462',
    projectId: 'infinityfeedflutterapp',
    storageBucket: 'infinityfeedflutterapp.appspot.com',
    iosClientId: '716879445462-37lsblim2bk2712c27caakk0k3q4r26u.apps.googleusercontent.com',
    iosBundleId: 'com.example.instagram.RunnerTests',
  );
}
